package com.chordsense.chordapp

class DefaultProgressions {

    companion object {
        val freeProgressions: Map<String, List<String>> = mapOf(

            "DefaultProgression:Basic I-V-vi-IV:C:Major:130:2024-10-28:fav_0" to listOf(
                "{'degree':0,'duration':4.0,'extension':'None','intervals':[0,7,12,16,19],'name':'Cmaj','numeral':'I','octave':4,'octaveBass':false,'offset':24,'position':0,'root':'C','symbol':'maj','type':'maj','voicing':'R P5 R M3 P5','voicingList':['R','P5','R','M3','P5']}",
                "{'degree':4,'duration':4.0,'extension':'None','intervals':[0,7,12,16,19],'name':'Gmaj','numeral':'V','octave':3,'octaveBass':false,'offset':19,'position':1,'root':'G','symbol':'maj','type':'maj','voicing':'R P5 R M3 P5','voicingList':['R','P5','R','M3','P5']}",
                "{'degree':5,'duration':4.0,'extension':'None','intervals':[0,7,12,15,19],'name':'Amin','numeral':'vi','octave':3,'octaveBass':false,'offset':21,'position':2,'root':'A','symbol':'min','type':'min','voicing':'R P5 R m3 P5','voicingList':['R','P5','R','m3','P5']}",
                "{'degree':3,'duration':4.0,'extension':'None','intervals':[0,7,12,16,19],'name':'Fmaj','numeral':'IV','octave':3,'octaveBass':false,'offset':17,'position':3,'root':'F','symbol':'maj','type':'maj','voicing':'R P5 R M3 P5','voicingList':['R','P5','R','M3','P5']}"),

            "DefaultProgression:Basic ii-V-iii-vi:C:Major:130:2024-10-28:fav_0" to listOf(
                "{'degree':1,'duration':3.0,'extension':'7','intervals':[0,3,7,10],'name':'Dmin7','numeral':'ii','octave':4,'octaveBass':false,'offset':26,'position':0,'root':'D','symbol':'min7','type':'min','voicing':'Root Position','voicingList':['R','m3','P5','m7']}",
                "{'degree':4,'duration':5.0,'extension':'7','intervals':[7,10,12,16],'name':'G7','numeral':'V','octave':3,'octaveBass':false,'offset':19,'position':1,'root':'G','symbol':'7','type':'maj','voicing':'P5 m7 R M3','voicingList':['P5','m7','R','M3']}",
                "{'degree':2,'duration':3.0,'extension':'7','intervals':[10,12,15,19],'name':'Emin7','numeral':'iii','octave':3,'octaveBass':false,'offset':16,'position':2,'root':'E','symbol':'min7','type':'min','voicing':'m7 R m3 P5','voicingList':['m7','R','m3','P5']}",
                "{'degree':5,'duration':5.0,'extension':'7','intervals':[7,10,12,15],'name':'Amin7','numeral':'vi','octave':3,'octaveBass':false,'offset':21,'position':3,'root':'A','symbol':'min7','type':'min','voicing':'P5 m7 R m3','voicingList':['P5','m7','R','m3']}",
                "{'degree':1,'duration':3.0,'extension':'7','intervals':[0,3,7,10],'name':'Dmin7','numeral':'ii','octave':4,'octaveBass':false,'offset':26,'position':4,'root':'D','symbol':'min7','type':'min','voicing':'Root Position','voicingList':['R','m3','P5','m7']}",
                "{'degree':4,'duration':5.0,'extension':'7','intervals':[7,10,12,16],'name':'G7','numeral':'V','octave':3,'octaveBass':false,'offset':19,'position':5,'root':'G','symbol':'7','type':'maj','voicing':'P5 m7 R M3','voicingList':['P5','m7','R','M3']}",
                "{'degree':2,'duration':3.0,'extension':'7','intervals':[10,12,15,19],'name':'Emin7','numeral':'iii','octave':3,'octaveBass':false,'offset':16,'position':6,'root':'E','symbol':'min7','type':'min','voicing':'m7 R m3 P5','voicingList':['m7','R','m3','P5']}",
                "{'degree':5,'duration':5.0,'extension':'7','intervals':[3,7,10,12],'name':'Amin7','numeral':'vi','octave':3,'octaveBass':false,'offset':21,'position':7,'root':'A','symbol':'min7','type':'min','voicing':'m3 P5 m7 R','voicingList':['m3','P5','m7','R']}"),

//            "DefaultProgression:Free3:A:Minor:130:2024-10-28:fav_0" to listOf(
//                "{'degree':0,'duration':4.0,'extension':'None','intervals':[-12,0,3,7],'name':'Amin','numeral':'i','octave':3,'octaveBass':false,'offset':21,'position':0,'root':'A','symbol':'min','type':'min','voicing':'R R m3 P5','voicingList':['R','R','m3','P5']}",
//                "{'degree':2,'duration':4.0,'extension':'None','intervals':[0,7,12,16],'name':'Cmaj','numeral':'III','octave':3,'octaveBass':false,'offset':12,'position':1,'root':'C','symbol':'maj','type':'maj','voicing':'R P5 R M3','voicingList':['R','P5','R','M3']}",
//                "{'degree':0,'duration':4.0,'extension':'None','intervals':[0,4,7,12],'name':'Dmaj','numeral':'IV','octave':3,'octaveBass':false,'offset':14,'position':2,'root':'D','symbol':'maj','type':'maj','voicing':'R M3 P5 R','voicingList':['R','M3','P5','R']}",
//                "{'degree':5,'duration':2.0,'extension':'None','intervals':[0,4,7,12],'name':'Fmaj','numeral':'VI','octave':3,'octaveBass':false,'offset':17,'position':3,'root':'F','symbol':'maj','type':'maj','voicing':'R M3 P5 R','voicingList':['R','M3','P5','R']}",
//                "{'degree':6,'duration':2.0,'extension':'None','intervals':[0,4,7,12],'name':'Gmaj','numeral':'VII','octave':3,'octaveBass':false,'offset':19,'position':4,'root':'G','symbol':'maj','type':'maj','voicing':'R M3 P5 R','voicingList':['R','M3','P5','R']}"),

            "DefaultProgression:Basic IV-V-iii-vi:C:Major:128:2024-10-28:fav_0" to listOf(
                "{'degree':3,'duration':4.0,'extension':'None','intervals':[0,7,12,16,19],'name':'Fmaj','numeral':'IV','octave':3,'octaveBass':false,'offset':17,'position':0,'root':'F','symbol':'maj','type':'maj','voicing':'R P5 R M3 P5','voicingList':['R','P5','R','M3','P5']}",
                "{'degree':4,'duration':4.0,'extension':'None','intervals':[0,7,12,16,19],'name':'Gmaj','numeral':'V','octave':3,'octaveBass':false,'offset':19,'position':1,'root':'G','symbol':'maj','type':'maj','voicing':'R P5 R M3 P5','voicingList':['R','P5','R','M3','P5']}",
                "{'degree':2,'duration':4.0,'extension':'None','intervals':[0,7,12,15,19],'name':'Emin','numeral':'iii','octave':3,'octaveBass':false,'offset':16,'position':2,'root':'E','symbol':'min','type':'min','voicing':'R P5 R m3 P5','voicingList':['R','P5','R','m3','P5']}",
                "{'degree':5,'duration':4.0,'extension':'None','intervals':[0,7,12,15,19],'name':'Amin','numeral':'vi','octave':3,'octaveBass':false,'offset':21,'position':3,'root':'A','symbol':'min','type':'min','voicing':'R P5 R m3 P5','voicingList':['R','P5','R','m3','P5']}"),

//            "DefaultProgression:Basic i-VII-iv-v:D:Minor:120:2024-10-28:fav_0" to listOf(
//                "{'degree':0,'duration':4.0,'extension':'None','intervals':[0,7,12,15,19],'name':'Dmin','numeral':'i','octave':4,'octaveBass':false,'offset':26,'position':0,'root':'D','symbol':'min','type':'min','voicing':'R P5 R m3 P5','voicingList':['R','P5','R','m3','P5']}",
//                "{'degree':6,'duration':4.0,'extension':'None','intervals':[0,7,12,16,19],'name':'Cmaj','numeral':'VII','octave':4,'octaveBass':false,'offset':24,'position':1,'root':'C','symbol':'maj','type':'maj','voicing':'R P5 R M3 P5','voicingList':['R','P5','R','M3','P5']}",
//                "{'degree':3,'duration':4.0,'extension':'None','intervals':[0,7,12,15,19],'name':'Gmin','numeral':'iv','octave':3,'octaveBass':false,'offset':19,'position':2,'root':'G','symbol':'min','type':'min','voicing':'R P5 R m3 P5','voicingList':['R','P5','R','m3','P5']}",
//                "{'degree':4,'duration':4.0,'extension':'None','intervals':[0,7,12,17,19],'name':'Asus4','numeral':'v','octave':3,'octaveBass':false,'offset':21,'position':3,'root':'A','symbol':'sus4','type':'sus4','voicing':'R P5 R P4 P5','voicingList':['R','P5','R','P4','P5']}"),

//            "DefaultProgression:Amin9-D13b9-Gmaj7-E7b9:G:Major:130:2024-11-11:fav_0" to listOf(
//                "{'degree':1,'duration':4.0,'extension':'9','intervals':[-12,0,3,7,10,14],'name':'Amin9','numeral':'ii','octave':3,'octaveBass':false,'offset':21,'position':0,'root':'A','symbol':'min9','type':'min','voicing':'R R m3 P5 m7 9','voicingList':['R','R','m3','P5','m7','9']}",
//                "{'degree':4,'duration':4.0,'extension':'13b9','intervals':[0,10,13,16,21],'name':'D13b9','numeral':'V','octave':3,'octaveBass':false,'offset':14,'position':1,'root':'D','symbol':'13b9','type':'maj','voicing':'R m7 b9 M3 13','voicingList':['R','m7','b9','M3','13']}",
//                "{'degree':0,'duration':4.0,'extension':'maj7','intervals':[0,11,16,19,23],'name':'Gmaj7','numeral':'I','octave':2,'octaveBass':false,'offset':7,'position':2,'root':'G','symbol':'maj7','type':'maj','voicing':'R M7 M3 P5 M7','voicingList':['R','M7','M3','P5','M7']}",
//                "{'degree':4,'duration':4.0,'extension':'7b9','intervals':[0,7,10,13,16],'name':'E7b9','numeral':'VI','octave':3,'octaveBass':false,'offset':16,'position':3,'root':'E','symbol':'7b9','type':'maj','voicing':'R P5 m7 b9 M3','voicingList':['R','P5','m7','b9','M3']}",
//                "{'degree':1,'duration':4.0,'extension':'9','intervals':[-12,0,3,7,10,14],'name':'Amin9','numeral':'ii','octave':3,'octaveBass':false,'offset':21,'position':4,'root':'A','symbol':'min9','type':'min','voicing':'R R m3 P5 m7 9','voicingList':['R','R','m3','P5','m7','9']}",
//                "{'degree':4,'duration':4.0,'extension':'13b9','intervals':[0,10,13,16,21],'name':'D13b9','numeral':'V','octave':3,'octaveBass':false,'offset':14,'position':5,'root':'D','symbol':'13b9','type':'maj','voicing':'R m7 b9 M3 13','voicingList':['R','m7','b9','M3','13']}",
//                "{'degree':0,'duration':4.0,'extension':'maj7','intervals':[0,11,16,19,23],'name':'Gmaj7','numeral':'I','octave':2,'octaveBass':false,'offset':7,'position':6,'root':'G','symbol':'maj7','type':'maj','voicing':'R M7 M3 P5 M7','voicingList':['R','M7','M3','P5','M7']}",
//                "{'degree':0,'duration':4.0,'extension':'dim7','intervals':[-12,0,3,6,9],'name':'G#dim7','numeral':'bii°','octave':3,'octaveBass':false,'offset':20,'position':7,'root':'G#','symbol':'dim7','type':'dim','voicing':'R R m3 b5 M6','voicingList':['R','R','m3','b5','M6']}"),
//

//                "DefaultProgression:Basic i-III-v-IV:D#:Minor:90:2024-10-28:fav_0" to listOf(
//                "{'degree':0,'duration':4.0,'extension':'None','intervals':[-12,0,7,15],'name':'D#min','numeral':'i','octave':3,'octaveBass':false,'offset':27,'position':0,'root':'D#','symbol':'min','type':'min','voicing':'R R P5 m3','voicingList':['R','R','P5','m3']}",
//                "{'degree':2,'duration':4.0,'extension':'None','intervals':[-12,0,7,16],'name':'F#maj','numeral':'III','octave':3,'octaveBass':false,'offset':30,'position':1,'root':'F#','symbol':'maj','type':'maj','voicing':'R R P5 M3','voicingList':['R','R','P5','M3']}",
//                "{'degree':4,'duration':4.0,'extension':'None','intervals':[-12,0,7,15],'name':'A#min','numeral':'v','octave':3,'octaveBass':false,'offset':34,'position':2,'root':'A#','symbol':'min','type':'min','voicing':'R R P5 m3','voicingList':['R','R','P5','m3']}",
//                "{'degree':0,'duration':4.0,'extension':'None','intervals':[-12,0,7,16],'name':'G#maj','numeral':'IV','octave':3,'octaveBass':false,'offset':32,'position':3,'root':'G#','symbol':'maj','type':'maj','voicing':'R R P5 M3','voicingList':['R','R','P5','M3']}",
//                "{'degree':0,'duration':4.0,'extension':'None','intervals':[-12,0,7,15],'name':'D#min','numeral':'i','octave':3,'octaveBass':false,'offset':27,'position':4,'root':'D#','symbol':'min','type':'min','voicing':'R R P5 m3','voicingList':['R','R','P5','m3']}",
//                "{'degree':2,'duration':4.0,'extension':'None','intervals':[-12,0,7,16],'name':'F#maj','numeral':'III','octave':3,'octaveBass':false,'offset':30,'position':5,'root':'F#','symbol':'maj','type':'maj','voicing':'R R P5 M3','voicingList':['R','R','P5','M3']}",
//                "{'degree':4,'duration':4.0,'extension':'None','intervals':[-12,0,7,15],'name':'A#min','numeral':'v','octave':3,'octaveBass':false,'offset':34,'position':6,'root':'A#','symbol':'min','type':'min','voicing':'R R P5 m3','voicingList':['R','R','P5','m3']}",
//                "{'degree':5,'duration':4.0,'extension':'None','intervals':[-12,0,7,16],'name':'Bmaj','numeral':'VI','octave':3,'octaveBass':false,'offset':35,'position':7,'root':'B','symbol':'maj','type':'maj','voicing':'R R P5 M3','voicingList':['R','R','P5','M3']}"),

            "DefaultProgression:Basic I-vi-IV-V:C:Major:128:2024-11-19:fav_0" to listOf(
                "{'degree':0,'duration':4.0,'extension':'None','intervals':[-12,0,4,7],'name':'Cmaj','numeral':'I','octave':4,'octaveBass':false,'offset':24,'position':0,'root':'C','symbol':'maj','type':'maj','voicing':'R R M3 P5','voicingList':['R','R','M3','P5']}",
                "{'degree':5,'duration':4.0,'extension':'None','intervals':[-12,3,7,12],'name':'Amin','numeral':'vi','octave':3,'octaveBass':false,'offset':21,'position':1,'root':'A','symbol':'min','type':'min','voicing':'R m3 P5 R','voicingList':['R','m3','P5','R']}",
                "{'degree':3,'duration':4.0,'extension':'None','intervals':[-12,7,12,16],'name':'Fmaj','numeral':'IV','octave':3,'octaveBass':false,'offset':17,'position':2,'root':'F','symbol':'maj','type':'maj','voicing':'R P5 R M3','voicingList':['R','P5','R','M3']}",
                "{'degree':4,'duration':4.0,'extension':'None','intervals':[-12,7,12,16],'name':'Gmaj','numeral':'V','octave':3,'octaveBass':false,'offset':19,'position':3,'root':'G','symbol':'maj','type':'maj','voicing':'R P5 R M3','voicingList':['R','P5','R','M3']}"),




            "DefaultProgression:Jazz ii-V-I-VI:C:Major:100:2024-11-21:fav_0" to listOf(
                "{'degree':1,'duration':4.0,'extension':'9','intervals':[0,3,7,10,14],'name':'Dmin9','numeral':'ii','octave':3,'octaveBass':false,'offset':14,'position':0,'root':'D','symbol':'min9','type':'min','voicing':'Root Position','voicingList':['R','m3','P5','m7','9']}",
                "{'degree':4,'duration':4.0,'extension':'13b9','intervals':[0,10,13,16,21],'name':'G13b9','numeral':'V','octave':2,'octaveBass':false,'offset':7,'position':1,'root':'G','symbol':'13b9','type':'maj','voicing':'R m7 b9 M3 13','voicingList':['R','m7','b9','M3','13']}",
                "{'degree':0,'duration':4.0,'extension':'maj9','intervals':[0,4,7,11,14],'name':'Cmaj9','numeral':'I','octave':3,'octaveBass':false,'offset':12,'position':2,'root':'C','symbol':'maj9','type':'maj','voicing':'Root Position','voicingList':['R','M3','P5','M7','9']}",
                "{'degree':0,'duration':4.0,'extension':'7b9','intervals':[0,7,10,13,16],'name':'A7b9','numeral':'VI','octave':2,'octaveBass':false,'offset':9,'position':3,'root':'A','symbol':'7b9','type':'maj','voicing':'R P5 m7 b9 M3','voicingList':['R','P5','m7','b9','M3']}",
                "{'degree':1,'duration':4.0,'extension':'9','intervals':[0,3,7,10,14],'name':'Dmin9','numeral':'ii','octave':3,'octaveBass':false,'offset':14,'position':4,'root':'D','symbol':'min9','type':'min','voicing':'Root Position','voicingList':['R','m3','P5','m7','9']}",
                "{'degree':4,'duration':4.0,'extension':'13b9','intervals':[0,10,13,16,21],'name':'G13b9','numeral':'V','octave':2,'octaveBass':false,'offset':7,'position':5,'root':'G','symbol':'13b9','type':'maj','voicing':'R m7 b9 M3 13','voicingList':['R','m7','b9','M3','13']}",
                "{'degree':0,'duration':4.0,'extension':'maj9','intervals':[0,4,7,11,14],'name':'Cmaj9','numeral':'I','octave':3,'octaveBass':false,'offset':12,'position':6,'root':'C','symbol':'maj9','type':'maj','voicing':'Root Position','voicingList':['R','M3','P5','M7','9']}",
                "{'degree':0,'duration':2.0,'extension':'7b9#5','intervals':[0,10,13,16,20],'name':'A7b9#5','numeral':'VI','octave':2,'octaveBass':false,'offset':9,'position':7,'root':'A','symbol':'7b9#5','type':'maj','voicing':'R m7 b9 M3 #5','voicingList':['R','m7','b9','M3','#5']}",
                "{'degree':0,'duration':2.0,'extension':'7b9','intervals':[0,10,13,16,19],'name':'A7b9','numeral':'VI','octave':2,'octaveBass':false,'offset':9,'position':8,'root':'A','symbol':'7b9','type':'maj','voicing':'R m7 b9 M3 P5','voicingList':['R','m7','b9','M3','P5']}"),


//            "DefaultProgression:Default2:D:Ionian:142:2024-09-11:fav_0" to listOf(
//                "{'degree':3,'duration':4.0,'extension':'maj9','intervals':[0,2,4,7,11],'name':'Gmaj9','numeral':'IV','octave':3,'offset':19,'position':0,'root':'G','symbol':'maj9','type':'maj','voicing':'R 9 M3 P5 M7','voicingList':['R','9','M3','P5','M7']}",
//                "{'degree':1,'duration':3.0,'extension':'9','intervals':[0,3,7,10,14],'name':'Emin9','numeral':'ii','octave':3,'offset':16,'position':1,'root':'E','symbol':'min9','type':'min','voicing':'Root Position','voicingList':['R','m3','P5','m7','9']}",
//                "{'degree':5,'duration':9.0,'extension':'9','intervals':[0,10,14,15,19],'name':'Bmin9','numeral':'vi','octave':2,'offset':11,'position':2,'root':'B','symbol':'min9','type':'min','voicing':'R m7 9 m3 P5','voicingList':['R','m7','9','m3','P5']}",
//                "{'degree':3,'duration':4.0,'extension':'maj9','intervals':[0,2,4,7,11],'name':'Gmaj9','numeral':'IV','octave':3,'offset':19,'position':3,'root':'G','symbol':'maj9','type':'maj','voicing':'R 9 M3 P5 M7','voicingList':['R','9','M3','P5','M7']}",
//                "{'degree':1,'duration':3.0,'extension':'9','intervals':[0,3,7,10,14],'name':'Emin9','numeral':'ii','octave':3,'offset':16,'position':4,'root':'E','symbol':'min9','type':'min','voicing':'Root Position','voicingList':['R','m3','P5','m7','9']}",
//                "{'degree':5,'duration':6.0,'extension':'9','intervals':[0,10,14,15,19],'name':'Bmin9','numeral':'vi','octave':2,'offset':11,'position':5,'root':'B','symbol':'min9','type':'min','voicing':'R m7 9 m3 P5','voicingList':['R','m7','9','m3','P5']}",
//                "{'degree':0,'duration':3.0,'extension':'maj9','intervals':[0,7,11,14,16],'name':'Dmaj9','numeral':'I','octave':3,'offset':14,'position':6,'root':'D','symbol':'maj9','type':'maj','voicing':'R P5 M7 9 M3','voicingList':['R','P5','M7','9','M3']}"),

//            "DefaultProgression:edm:G:Major:128:2024-10-02:fav_0" to listOf(
//                "{'degree':3,'duration':3.0,'extension':'maj7','intervals':[0,7,11,14,19],'name':'Cmaj7sus2','numeral':'IV','octave':3,'offset':12,'position':0,'root':'C','symbol':'maj7sus2','type':'sus2','voicing':'R P5 M7 M2','voicingList':['R','P5','M7','M2','P5']}",
//                "{'degree':0,'duration':5.0,'extension':'maj7','intervals':[0,7,14,19,23],'name':'Gmaj7sus2','numeral':'I','octave':2,'offset':7,'position':1,'root':'G','symbol':'maj7sus2','type':'sus2','voicing':'R P5 M2 P5 M7','voicingList':['R','P5','M2','P5','M7']}",
//                "{'degree':1,'duration':8.0,'extension':'7(11)','intervals':[0,7,15,17,22],'name':'Amin7(11)','numeral':'ii','octave':2,'offset':9,'position':2,'root':'A','symbol':'min7(11)','type':'min','voicing':'R P5 m3 11 m7','voicingList':['R','P5','m3','11','m7']}"),
//
//
//            "DefaultProgression:edm2:D:Major:180:2024-10-02:fav_0" to listOf(
//                "{'degree':3,'duration':3.0,'extension':'add9','intervals':[0,7,14,16],'name':'Gadd9','numeral':'IV','octave':4,'offset':31,'position':0,'root':'G','symbol':'add9','type':'maj','voicing':'R P5 9 M3','voicingList':['R','P5','9','M3']}",
//                "{'degree':0,'duration':5.0,'extension':'None','intervals':[0,7,12,16],'name':'Dmaj','numeral':'I','octave':4,'offset':26,'position':1,'root':'D','symbol':'maj','type':'maj','voicing':'R P5 R M3','voicingList':['R','P5','R','M3']}",
//                "{'degree':4,'duration':3.0,'extension':'None','intervals':[0,4,7,16],'name':'Amaj','numeral':'V','octave':4,'offset':33,'position':2,'root':'A','symbol':'maj','type':'maj','voicing':'Root Position','voicingList':['R','M3','P5','M3']}",
//                "{'degree':5,'duration':5.0,'extension':'7','intervals':[0,7,10,15],'name':'Bmin7','numeral':'vi','octave':4,'offset':35,'position':3,'root':'B','symbol':'min7','type':'min','voicing':'R P5 m7 m3','voicingList':['R','P5','m7','m3']}",
//                "{'degree':3,'duration':3.0,'extension':'add9','intervals':[0,7,14,16],'name':'Gadd9','numeral':'IV','octave':4,'offset':31,'position':4,'root':'G','symbol':'add9','type':'maj','voicing':'R P5 9 M3','voicingList':['R','P5','9','M3']}",
//                "{'degree':0,'duration':5.0,'extension':'None','intervals':[0,7,12,16],'name':'Dmaj','numeral':'I','octave':4,'offset':26,'position':5,'root':'D','symbol':'maj','type':'maj','voicing':'R P5 R M3','voicingList':['R','P5','R','M3']}",
//                "{'degree':4,'duration':3.0,'extension':'None','intervals':[0,4,7,12],'name':'Amaj','numeral':'V','octave':4,'offset':33,'position':6,'root':'A','symbol':'maj','type':'maj','voicing':'Root Position','voicingList':['R','M3','P5','R']}",
//                "{'degree':5,'duration':5.0,'extension':'7','intervals':[0,7,10,15],'name':'Bmin7','numeral':'vi','octave':3,'offset':23,'position':7,'root':'B','symbol':'min7','type':'min','voicing':'R P5 m7 m3','voicingList':['R','P5','m7','m3']}"),
//
//            "DefaultProgression:edm3:A:Minor:128:2024-10-02:fav_0" to listOf(
//                "{'degree':0,'duration':2.5,'extension':'7','intervals':[0,3,7,10],'name':'Amin7','numeral':'I','octave':3,'offset':21,'position':0,'root':'A','symbol':'min7','type':'min','voicing':'Root Position','voicingList':['R','m3','P5','m7']}",
//                "{'degree':6,'duration':1.0,'extension':'6','intervals':[0,4,7,9],'name':'G6','numeral':'VII','octave':3,'offset':19,'position':1,'root':'G','symbol':'6','type':'maj','voicing':'Root Position','voicingList':['R','M3','P5','M6']}",
//                "{'degree':5,'duration':2.0,'extension':'maj7','intervals':[0,4,7,11],'name':'Fmaj7','numeral':'VI','octave':3,'offset':17,'position':2,'root':'F','symbol':'maj7','type':'maj','voicing':'Root Position','voicingList':['R','M3','P5','M7']}",
//                "{'degree':5,'duration':2.5,'extension':'maj7','intervals':[0,4,7,11],'name':'Fmaj7','numeral':'VI','octave':3,'offset':17,'position':3,'root':'F','symbol':'maj7','type':'maj','voicing':'Root Position','voicingList':['R','M3','P5','M7']}",
//                "{'degree':3,'duration':2.5,'extension':'7','intervals':[0,3,7,10],'name':'Dmin7','numeral':'iv','octave':3,'offset':14,'position':4,'root':'D','symbol':'min7','type':'min','voicing':'Root Position','voicingList':['R','m3','P5','m7']}",
//                "{'degree':4,'duration':1.0,'extension':'7','intervals':[0,3,7,10],'name':'Emin7','numeral':'v','octave':3,'offset':16,'position':5,'root':'E','symbol':'min7','type':'min','voicing':'Root Position','voicingList':['R','m3','P5','m7']}",
//                "{'degree':5,'duration':2.0,'extension':'maj7','intervals':[0,4,7,11],'name':'Fmaj7','numeral':'VI','octave':3,'offset':17,'position':6,'root':'F','symbol':'maj7','type':'maj','voicing':'Root Position','voicingList':['R','M3','P5','M7']}",
//                "{'degree':5,'duration':2.5,'extension':'maj7','intervals':[0,4,7,11],'name':'Fmaj7','numeral':'VI','octave':3,'offset':17,'position':7,'root':'F','symbol':'maj7','type':'maj','voicing':'Root Position','voicingList':['R','M3','P5','M7']}"),
//
//
//            "DefaultProgression:Jazz2:C:Minor:140:2024-10-15:fav_0" to listOf(
//                "{'degree':0,'duration':4.0,'extension':'9','intervals':[-12,3,7,10,14],'name':'Amin9','numeral':'I','octave':3,'octaveBass':true,'offset':21,'position':0,'root':'A','symbol':'min9','type':'min','voicing':'Root Position','voicingList':['R','m3','P5','m7','9']}",
//                "{'degree':4,'duration':4.0,'extension':'7#9','intervals':[-12,4,7,10,15],'name':'E7#9','numeral':'V','octave':3,'octaveBass':true,'offset':16,'position':1,'root':'E','symbol':'7#9','type':'maj','voicing':'Root Position','voicingList':['R','M3','P5','m7','#9']}",
//                "{'degree':3,'duration':4.0,'extension':'9','intervals':[-12,3,7,10,14],'name':'Dmin9','numeral':'iv','octave':3,'octaveBass':true,'offset':14,'position':2,'root':'D','symbol':'min9','type':'min','voicing':'Root Position','voicingList':['R','m3','P5','m7','9']}",
//                "{'degree':4,'duration':4.0,'extension':'7#9','intervals':[-12,4,7,10,15],'name':'E7#9','numeral':'V','octave':3,'octaveBass':true,'offset':16,'position':3,'root':'E','symbol':'7#9','type':'maj','voicing':'Root Position','voicingList':['R','M3','P5','m7','#9']}",
//                "{'degree':0,'duration':4.0,'extension':'9','intervals':[-12,3,7,10,14],'name':'Amin9','numeral':'I','octave':3,'octaveBass':true,'offset':21,'position':4,'root':'A','symbol':'min9','type':'min','voicing':'Root Position','voicingList':['R','m3','P5','m7','9']}",
//                "{'degree':4,'duration':4.0,'extension':'7#9','intervals':[-12,4,7,10,15],'name':'E7#9','numeral':'V','octave':3,'octaveBass':true,'offset':16,'position':5,'root':'E','symbol':'7#9','type':'maj','voicing':'Root Position','voicingList':['R','M3','P5','m7','#9']}",
//                "{'degree':3,'duration':4.0,'extension':'9','intervals':[-12,3,7,10,14],'name':'Dmin9','numeral':'iv','octave':3,'octaveBass':true,'offset':14,'position':6,'root':'D','symbol':'min9','type':'min','voicing':'Root Position','voicingList':['R','m3','P5','m7','9']}",
//                "{'degree':4,'duration':4.0,'extension':'7b9','intervals':[-12,1,4,7,10],'name':'E7b9','numeral':'V','octave':3,'octaveBass':true,'offset':16,'position':7,'root':'E','symbol':'7b9','type':'maj','voicing':'R b9 M3 P5 m7','voicingList':['R','b9','M3','P5','m7']}"),
//
//            "DefaultProgression:Jazz3:D:Minor:140:2024-10-15:fav_0" to listOf(
//                "{'degree':3,'duration':4.0,'extension':'9','intervals':[0,10,15,19,26],'name':'Gmin9','numeral':'iv','octave':2,'octaveBass':false,'offset':7,'position':0,'root':'G','symbol':'min9','type':'min','voicing':'R m7 m3 P5 9','voicingList':['R','m7','m3','P5','9']}",
//                "{'degree':4,'duration':4.0,'extension':'9#11','intervals':[0,7,16,22,26,30],'name':'D#9#11','numeral':'bII','octave':2,'octaveBass':false,'offset':3,'position':1,'root':'D#','symbol':'9#11','type':'maj','voicing':'R P5 M3 m7 9 #11','voicingList':['R','P5','M3','m7','9','#11']}",
//                "{'degree':0,'duration':4.0,'extension':'9','intervals':[-12,3,7,10,14,19],'name':'Dmin9','numeral':'i','octave':3,'octaveBass':true,'offset':14,'position':2,'root':'D','symbol':'min9','type':'min','voicing':'R m3 P5 m7 9 P5','voicingList':['R','m3','P5','m7','9','P5']}",
//                "{'degree':4,'duration':4.0,'extension':'13','intervals':[0,10,16,21,26],'name':'G#13','numeral':'bV','octave':2,'octaveBass':false,'offset':8,'position':3,'root':'G#','symbol':'13','type':'maj','voicing':'R m7 M3 13 9','voicingList':['R','m7','M3','13','9']}"),
//
//            "DefaultProgression:idk12431:A:Major:100:2024-10-25:fav_0" to listOf(
//                "{'degree':0,'duration':4.0,'extension':'maj7','intervals':[0,11,16,19,23],'name':'Dmaj7','numeral':'I','octave':3,'octaveBass':false,'offset':14,'position':0,'root':'D','symbol':'maj7','type':'maj','voicing':'R M7 M3 P5 M7','voicingList':['R','M7','M3','P5','M7']}",
//                "{'degree':5,'duration':4.0,'extension':'9','intervals':[0,10,15,19,26],'name':'Bmin9','numeral':'vi','octave':2,'octaveBass':false,'offset':11,'position':1,'root':'B','symbol':'min9','type':'min','voicing':'R m7 m3 P5 9','voicingList':['R','m7','m3','P5','9']}",
//                "{'degree':5,'duration':4.0,'extension':'9','intervals':[0,7,10,14,17],'name':'F#9sus4','numeral':'vi','octave':3,'octaveBass':false,'offset':18,'position':2,'root':'F#','symbol':'9sus4','type':'sus4','voicing':'R P5 m7 9 P4','voicingList':['R','P5','m7','9','P4']}",
//                "{'degree':2,'duration':2.0,'extension':'7','intervals':[0,10,15,19,22],'name':'C#min7','numeral':'iii','octave':3,'octaveBass':false,'offset':13,'position':3,'root':'C#','symbol':'min7','type':'min','voicing':'R m7 m3 P5 m7','voicingList':['R','m7','m3','P5','m7']}",
//                "{'degree':4,'duration':2.0,'extension':'6','intervals':[0,9,16,19,24],'name':'E6','numeral':'V','octave':3,'octaveBass':false,'offset':16,'position':4,'root':'E','symbol':'6','type':'maj','voicing':'R M6 M3 P5 R','voicingList':['R','M6','M3','P5','R']}"),
//
//
//            "DefaultProgression:Abmaj9-Am11-Ebmaj9-Fmaj9:F:Major:140:2024-10-25:fav_0" to listOf(
//                "{'degree':0,'duration':3.0,'extension':'maj9','intervals':[0,11,14,16,19,23],'name':'G#maj9','numeral':'bIII','octave':2,'octaveBass':false,'offset':8,'position':0,'root':'G#','symbol':'maj9','type':'maj','voicing':'R M7 9 M3 P5 M7','voicingList':['R','M7','9','M3','P5','M7']}",
//                "{'degree':0,'duration':5.0,'extension':'11','intervals':[0,10,14,15,17,19,22],'name':'Amin11','numeral':'iii','octave':2,'octaveBass':false,'offset':9,'position':1,'root':'A','symbol':'min11','type':'min','voicing':'R m7 9 m3 11 P5 m7','voicingList':['R','m7','9','m3','11','P5','m7']}",
//                "{'degree':0,'duration':3.0,'extension':'maj9','intervals':[0,4,7,11,14,16],'name':'D#maj9','numeral':'bVII','octave':3,'octaveBass':false,'offset':15,'position':2,'root':'D#','symbol':'maj9','type':'maj','voicing':'R M3 P5 M7 9 M3','voicingList':['R','M3','P5','M7','9','M3']}",
//                "{'degree':0,'duration':5.0,'extension':'maj9','intervals':[0,4,7,11,14],'name':'Fmaj9','numeral':'I','octave':3,'octaveBass':false,'offset':17,'position':3,'root':'F','symbol':'maj9','type':'maj','voicing':'R M3 P5 M7 9','voicingList':['R','M3','P5','M7','9']}"),


//            "DefaultProgression:Free1:C:Major:130:2024-10-28:fav_0"
//            "DefaultProgression:Free1:C:Major:130:2024-10-28:fav_0"


        )

        val progressions: Map<String, List<String>> = mapOf(                  "DefaultProgression:Basic I-V-vi-IV:C:Major:130:2024-10-28:fav_0" to listOf(
            "{'degree':0,'duration':4.0,'extension':'None','intervals':[0,7,12,16,19],'name':'Cmaj','numeral':'I','octave':4,'octaveBass':false,'offset':24,'position':0,'root':'C','symbol':'maj','type':'maj','voicing':'R P5 R M3 P5','voicingList':['R','P5','R','M3','P5']}",
            "{'degree':4,'duration':4.0,'extension':'None','intervals':[0,7,12,16,19],'name':'Gmaj','numeral':'V','octave':3,'octaveBass':false,'offset':19,'position':1,'root':'G','symbol':'maj','type':'maj','voicing':'R P5 R M3 P5','voicingList':['R','P5','R','M3','P5']}",
            "{'degree':5,'duration':4.0,'extension':'None','intervals':[0,7,12,15,19],'name':'Amin','numeral':'vi','octave':3,'octaveBass':false,'offset':21,'position':2,'root':'A','symbol':'min','type':'min','voicing':'R P5 R m3 P5','voicingList':['R','P5','R','m3','P5']}",
            "{'degree':3,'duration':4.0,'extension':'None','intervals':[0,7,12,16,19],'name':'Fmaj','numeral':'IV','octave':3,'octaveBass':false,'offset':17,'position':3,'root':'F','symbol':'maj','type':'maj','voicing':'R P5 R M3 P5','voicingList':['R','P5','R','M3','P5']}"),

            "DefaultProgression:Basic ii-V-iii-vi:C:Major:130:2024-10-28:fav_0" to listOf(
                "{'degree':1,'duration':3.0,'extension':'7','intervals':[0,3,7,10],'name':'Dmin7','numeral':'ii','octave':4,'octaveBass':false,'offset':26,'position':0,'root':'D','symbol':'min7','type':'min','voicing':'Root Position','voicingList':['R','m3','P5','m7']}",
                "{'degree':4,'duration':5.0,'extension':'7','intervals':[7,10,12,16],'name':'G7','numeral':'V','octave':3,'octaveBass':false,'offset':19,'position':1,'root':'G','symbol':'7','type':'maj','voicing':'P5 m7 R M3','voicingList':['P5','m7','R','M3']}",
                "{'degree':2,'duration':3.0,'extension':'7','intervals':[10,12,15,19],'name':'Emin7','numeral':'iii','octave':3,'octaveBass':false,'offset':16,'position':2,'root':'E','symbol':'min7','type':'min','voicing':'m7 R m3 P5','voicingList':['m7','R','m3','P5']}",
                "{'degree':5,'duration':5.0,'extension':'7','intervals':[7,10,12,15],'name':'Amin7','numeral':'vi','octave':3,'octaveBass':false,'offset':21,'position':3,'root':'A','symbol':'min7','type':'min','voicing':'P5 m7 R m3','voicingList':['P5','m7','R','m3']}",
                "{'degree':1,'duration':3.0,'extension':'7','intervals':[0,3,7,10],'name':'Dmin7','numeral':'ii','octave':4,'octaveBass':false,'offset':26,'position':4,'root':'D','symbol':'min7','type':'min','voicing':'Root Position','voicingList':['R','m3','P5','m7']}",
                "{'degree':4,'duration':5.0,'extension':'7','intervals':[7,10,12,16],'name':'G7','numeral':'V','octave':3,'octaveBass':false,'offset':19,'position':5,'root':'G','symbol':'7','type':'maj','voicing':'P5 m7 R M3','voicingList':['P5','m7','R','M3']}",
                "{'degree':2,'duration':3.0,'extension':'7','intervals':[10,12,15,19],'name':'Emin7','numeral':'iii','octave':3,'octaveBass':false,'offset':16,'position':6,'root':'E','symbol':'min7','type':'min','voicing':'m7 R m3 P5','voicingList':['m7','R','m3','P5']}",
                "{'degree':5,'duration':5.0,'extension':'7','intervals':[3,7,10,12],'name':'Amin7','numeral':'vi','octave':3,'octaveBass':false,'offset':21,'position':7,'root':'A','symbol':'min7','type':'min','voicing':'m3 P5 m7 R','voicingList':['m3','P5','m7','R']}"),

//            "DefaultProgression:Free3:A:Minor:130:2024-10-28:fav_0" to listOf(
//                "{'degree':0,'duration':4.0,'extension':'None','intervals':[-12,0,3,7],'name':'Amin','numeral':'i','octave':3,'octaveBass':false,'offset':21,'position':0,'root':'A','symbol':'min','type':'min','voicing':'R R m3 P5','voicingList':['R','R','m3','P5']}",
//                "{'degree':2,'duration':4.0,'extension':'None','intervals':[0,7,12,16],'name':'Cmaj','numeral':'III','octave':3,'octaveBass':false,'offset':12,'position':1,'root':'C','symbol':'maj','type':'maj','voicing':'R P5 R M3','voicingList':['R','P5','R','M3']}",
//                "{'degree':0,'duration':4.0,'extension':'None','intervals':[0,4,7,12],'name':'Dmaj','numeral':'IV','octave':3,'octaveBass':false,'offset':14,'position':2,'root':'D','symbol':'maj','type':'maj','voicing':'R M3 P5 R','voicingList':['R','M3','P5','R']}",
//                "{'degree':5,'duration':2.0,'extension':'None','intervals':[0,4,7,12],'name':'Fmaj','numeral':'VI','octave':3,'octaveBass':false,'offset':17,'position':3,'root':'F','symbol':'maj','type':'maj','voicing':'R M3 P5 R','voicingList':['R','M3','P5','R']}",
//                "{'degree':6,'duration':2.0,'extension':'None','intervals':[0,4,7,12],'name':'Gmaj','numeral':'VII','octave':3,'octaveBass':false,'offset':19,'position':4,'root':'G','symbol':'maj','type':'maj','voicing':'R M3 P5 R','voicingList':['R','M3','P5','R']}"),

            "DefaultProgression:Basic IV-V-iii-vi:C:Major:128:2024-10-28:fav_0" to listOf(
                "{'degree':3,'duration':4.0,'extension':'None','intervals':[0,7,12,16,19],'name':'Fmaj','numeral':'IV','octave':3,'octaveBass':false,'offset':17,'position':0,'root':'F','symbol':'maj','type':'maj','voicing':'R P5 R M3 P5','voicingList':['R','P5','R','M3','P5']}",
                "{'degree':4,'duration':4.0,'extension':'None','intervals':[0,7,12,16,19],'name':'Gmaj','numeral':'V','octave':3,'octaveBass':false,'offset':19,'position':1,'root':'G','symbol':'maj','type':'maj','voicing':'R P5 R M3 P5','voicingList':['R','P5','R','M3','P5']}",
                "{'degree':2,'duration':4.0,'extension':'None','intervals':[0,7,12,15,19],'name':'Emin','numeral':'iii','octave':3,'octaveBass':false,'offset':16,'position':2,'root':'E','symbol':'min','type':'min','voicing':'R P5 R m3 P5','voicingList':['R','P5','R','m3','P5']}",
                "{'degree':5,'duration':4.0,'extension':'None','intervals':[0,7,12,15,19],'name':'Amin','numeral':'vi','octave':3,'octaveBass':false,'offset':21,'position':3,'root':'A','symbol':'min','type':'min','voicing':'R P5 R m3 P5','voicingList':['R','P5','R','m3','P5']}"),

//            "DefaultProgression:Basic i-VII-iv-v:D:Minor:120:2024-10-28:fav_0" to listOf(
//                "{'degree':0,'duration':4.0,'extension':'None','intervals':[0,7,12,15,19],'name':'Dmin','numeral':'i','octave':4,'octaveBass':false,'offset':26,'position':0,'root':'D','symbol':'min','type':'min','voicing':'R P5 R m3 P5','voicingList':['R','P5','R','m3','P5']}",
//                "{'degree':6,'duration':4.0,'extension':'None','intervals':[0,7,12,16,19],'name':'Cmaj','numeral':'VII','octave':4,'octaveBass':false,'offset':24,'position':1,'root':'C','symbol':'maj','type':'maj','voicing':'R P5 R M3 P5','voicingList':['R','P5','R','M3','P5']}",
//                "{'degree':3,'duration':4.0,'extension':'None','intervals':[0,7,12,15,19],'name':'Gmin','numeral':'iv','octave':3,'octaveBass':false,'offset':19,'position':2,'root':'G','symbol':'min','type':'min','voicing':'R P5 R m3 P5','voicingList':['R','P5','R','m3','P5']}",
//                "{'degree':4,'duration':4.0,'extension':'None','intervals':[0,7,12,17,19],'name':'Asus4','numeral':'v','octave':3,'octaveBass':false,'offset':21,'position':3,'root':'A','symbol':'sus4','type':'sus4','voicing':'R P5 R P4 P5','voicingList':['R','P5','R','P4','P5']}"),

//            "DefaultProgression:Amin9-D13b9-Gmaj7-E7b9:G:Major:130:2024-11-11:fav_0" to listOf(
//                "{'degree':1,'duration':4.0,'extension':'9','intervals':[-12,0,3,7,10,14],'name':'Amin9','numeral':'ii','octave':3,'octaveBass':false,'offset':21,'position':0,'root':'A','symbol':'min9','type':'min','voicing':'R R m3 P5 m7 9','voicingList':['R','R','m3','P5','m7','9']}",
//                "{'degree':4,'duration':4.0,'extension':'13b9','intervals':[0,10,13,16,21],'name':'D13b9','numeral':'V','octave':3,'octaveBass':false,'offset':14,'position':1,'root':'D','symbol':'13b9','type':'maj','voicing':'R m7 b9 M3 13','voicingList':['R','m7','b9','M3','13']}",
//                "{'degree':0,'duration':4.0,'extension':'maj7','intervals':[0,11,16,19,23],'name':'Gmaj7','numeral':'I','octave':2,'octaveBass':false,'offset':7,'position':2,'root':'G','symbol':'maj7','type':'maj','voicing':'R M7 M3 P5 M7','voicingList':['R','M7','M3','P5','M7']}",
//                "{'degree':4,'duration':4.0,'extension':'7b9','intervals':[0,7,10,13,16],'name':'E7b9','numeral':'VI','octave':3,'octaveBass':false,'offset':16,'position':3,'root':'E','symbol':'7b9','type':'maj','voicing':'R P5 m7 b9 M3','voicingList':['R','P5','m7','b9','M3']}",
//                "{'degree':1,'duration':4.0,'extension':'9','intervals':[-12,0,3,7,10,14],'name':'Amin9','numeral':'ii','octave':3,'octaveBass':false,'offset':21,'position':4,'root':'A','symbol':'min9','type':'min','voicing':'R R m3 P5 m7 9','voicingList':['R','R','m3','P5','m7','9']}",
//                "{'degree':4,'duration':4.0,'extension':'13b9','intervals':[0,10,13,16,21],'name':'D13b9','numeral':'V','octave':3,'octaveBass':false,'offset':14,'position':5,'root':'D','symbol':'13b9','type':'maj','voicing':'R m7 b9 M3 13','voicingList':['R','m7','b9','M3','13']}",
//                "{'degree':0,'duration':4.0,'extension':'maj7','intervals':[0,11,16,19,23],'name':'Gmaj7','numeral':'I','octave':2,'octaveBass':false,'offset':7,'position':6,'root':'G','symbol':'maj7','type':'maj','voicing':'R M7 M3 P5 M7','voicingList':['R','M7','M3','P5','M7']}",
//                "{'degree':0,'duration':4.0,'extension':'dim7','intervals':[-12,0,3,6,9],'name':'G#dim7','numeral':'bii°','octave':3,'octaveBass':false,'offset':20,'position':7,'root':'G#','symbol':'dim7','type':'dim','voicing':'R R m3 b5 M6','voicingList':['R','R','m3','b5','M6']}"),
//

//                "DefaultProgression:Basic i-III-v-IV:D#:Minor:90:2024-10-28:fav_0" to listOf(
//                "{'degree':0,'duration':4.0,'extension':'None','intervals':[-12,0,7,15],'name':'D#min','numeral':'i','octave':3,'octaveBass':false,'offset':27,'position':0,'root':'D#','symbol':'min','type':'min','voicing':'R R P5 m3','voicingList':['R','R','P5','m3']}",
//                "{'degree':2,'duration':4.0,'extension':'None','intervals':[-12,0,7,16],'name':'F#maj','numeral':'III','octave':3,'octaveBass':false,'offset':30,'position':1,'root':'F#','symbol':'maj','type':'maj','voicing':'R R P5 M3','voicingList':['R','R','P5','M3']}",
//                "{'degree':4,'duration':4.0,'extension':'None','intervals':[-12,0,7,15],'name':'A#min','numeral':'v','octave':3,'octaveBass':false,'offset':34,'position':2,'root':'A#','symbol':'min','type':'min','voicing':'R R P5 m3','voicingList':['R','R','P5','m3']}",
//                "{'degree':0,'duration':4.0,'extension':'None','intervals':[-12,0,7,16],'name':'G#maj','numeral':'IV','octave':3,'octaveBass':false,'offset':32,'position':3,'root':'G#','symbol':'maj','type':'maj','voicing':'R R P5 M3','voicingList':['R','R','P5','M3']}",
//                "{'degree':0,'duration':4.0,'extension':'None','intervals':[-12,0,7,15],'name':'D#min','numeral':'i','octave':3,'octaveBass':false,'offset':27,'position':4,'root':'D#','symbol':'min','type':'min','voicing':'R R P5 m3','voicingList':['R','R','P5','m3']}",
//                "{'degree':2,'duration':4.0,'extension':'None','intervals':[-12,0,7,16],'name':'F#maj','numeral':'III','octave':3,'octaveBass':false,'offset':30,'position':5,'root':'F#','symbol':'maj','type':'maj','voicing':'R R P5 M3','voicingList':['R','R','P5','M3']}",
//                "{'degree':4,'duration':4.0,'extension':'None','intervals':[-12,0,7,15],'name':'A#min','numeral':'v','octave':3,'octaveBass':false,'offset':34,'position':6,'root':'A#','symbol':'min','type':'min','voicing':'R R P5 m3','voicingList':['R','R','P5','m3']}",
//                "{'degree':5,'duration':4.0,'extension':'None','intervals':[-12,0,7,16],'name':'Bmaj','numeral':'VI','octave':3,'octaveBass':false,'offset':35,'position':7,'root':'B','symbol':'maj','type':'maj','voicing':'R R P5 M3','voicingList':['R','R','P5','M3']}"),

            "DefaultProgression:Basic I-vi-IV-V:C:Major:128:2024-11-19:fav_0" to listOf(
                "{'degree':0,'duration':4.0,'extension':'None','intervals':[-12,0,4,7],'name':'Cmaj','numeral':'I','octave':4,'octaveBass':false,'offset':24,'position':0,'root':'C','symbol':'maj','type':'maj','voicing':'R R M3 P5','voicingList':['R','R','M3','P5']}",
                "{'degree':5,'duration':4.0,'extension':'None','intervals':[-12,3,7,12],'name':'Amin','numeral':'vi','octave':3,'octaveBass':false,'offset':21,'position':1,'root':'A','symbol':'min','type':'min','voicing':'R m3 P5 R','voicingList':['R','m3','P5','R']}",
                "{'degree':3,'duration':4.0,'extension':'None','intervals':[-12,7,12,16],'name':'Fmaj','numeral':'IV','octave':3,'octaveBass':false,'offset':17,'position':2,'root':'F','symbol':'maj','type':'maj','voicing':'R P5 R M3','voicingList':['R','P5','R','M3']}",
                "{'degree':4,'duration':4.0,'extension':'None','intervals':[-12,7,12,16],'name':'Gmaj','numeral':'V','octave':3,'octaveBass':false,'offset':19,'position':3,'root':'G','symbol':'maj','type':'maj','voicing':'R P5 R M3','voicingList':['R','P5','R','M3']}"),




            "DefaultProgression:Jazz ii-V-I-VI:C:Major:100:2024-11-21:fav_0" to listOf(
                "{'degree':1,'duration':4.0,'extension':'9','intervals':[0,3,7,10,14],'name':'Dmin9','numeral':'ii','octave':3,'octaveBass':false,'offset':14,'position':0,'root':'D','symbol':'min9','type':'min','voicing':'Root Position','voicingList':['R','m3','P5','m7','9']}",
                "{'degree':4,'duration':4.0,'extension':'13b9','intervals':[0,10,13,16,21],'name':'G13b9','numeral':'V','octave':2,'octaveBass':false,'offset':7,'position':1,'root':'G','symbol':'13b9','type':'maj','voicing':'R m7 b9 M3 13','voicingList':['R','m7','b9','M3','13']}",
                "{'degree':0,'duration':4.0,'extension':'maj9','intervals':[0,4,7,11,14],'name':'Cmaj9','numeral':'I','octave':3,'octaveBass':false,'offset':12,'position':2,'root':'C','symbol':'maj9','type':'maj','voicing':'Root Position','voicingList':['R','M3','P5','M7','9']}",
                "{'degree':0,'duration':4.0,'extension':'7b9','intervals':[0,7,10,13,16],'name':'A7b9','numeral':'VI','octave':2,'octaveBass':false,'offset':9,'position':3,'root':'A','symbol':'7b9','type':'maj','voicing':'R P5 m7 b9 M3','voicingList':['R','P5','m7','b9','M3']}",
                "{'degree':1,'duration':4.0,'extension':'9','intervals':[0,3,7,10,14],'name':'Dmin9','numeral':'ii','octave':3,'octaveBass':false,'offset':14,'position':4,'root':'D','symbol':'min9','type':'min','voicing':'Root Position','voicingList':['R','m3','P5','m7','9']}",
                "{'degree':4,'duration':4.0,'extension':'13b9','intervals':[0,10,13,16,21],'name':'G13b9','numeral':'V','octave':2,'octaveBass':false,'offset':7,'position':5,'root':'G','symbol':'13b9','type':'maj','voicing':'R m7 b9 M3 13','voicingList':['R','m7','b9','M3','13']}",
                "{'degree':0,'duration':4.0,'extension':'maj9','intervals':[0,4,7,11,14],'name':'Cmaj9','numeral':'I','octave':3,'octaveBass':false,'offset':12,'position':6,'root':'C','symbol':'maj9','type':'maj','voicing':'Root Position','voicingList':['R','M3','P5','M7','9']}",
                "{'degree':0,'duration':2.0,'extension':'7b9#5','intervals':[0,10,13,16,20],'name':'A7b9#5','numeral':'VI','octave':2,'octaveBass':false,'offset':9,'position':7,'root':'A','symbol':'7b9#5','type':'maj','voicing':'R m7 b9 M3 #5','voicingList':['R','m7','b9','M3','#5']}",
                "{'degree':0,'duration':2.0,'extension':'7b9','intervals':[0,10,13,16,19],'name':'A7b9','numeral':'VI','octave':2,'octaveBass':false,'offset':9,'position':8,'root':'A','symbol':'7b9','type':'maj','voicing':'R m7 b9 M3 P5','voicingList':['R','m7','b9','M3','P5']}"),

            "PremiumProgression:Jazz 1:D:Major:115:2024-12-26:fav_0" to listOf(
                "{'degree':3,'duration':3.5,'extension':'6/9','intervals':[-12,4,7,9,14],'name':'D6/9','numeral':'I','octave':3,'octaveBass':false,'offset':14,'position':0,'root':'D','symbol':'6/9','type':'maj','voicing':'Root Position','voicingList':['R','M3','P5','M6','9']}",
                "{'degree':3,'duration':4.5,'extension':'6','intervals':[7,12,16,21,24],'name':'D6','numeral':'I','octave':2,'octaveBass':false,'offset':2,'position':1,'root':'D','symbol':'6','type':'maj','voicing':'P5 R M3 M6 R','voicingList':['P5','R','M3','M6','R']}",
                "{'degree':4,'duration':3.5,'extension':'9','intervals':[-12,4,7,10,14],'name':'E9','numeral':'II','octave':3,'octaveBass':false,'offset':16,'position':2,'root':'E','symbol':'9','type':'maj','voicing':'Root Position','voicingList':['R','M3','P5','m7','9']}",
                "{'degree':4,'duration':4.5,'extension':'7','intervals':[7,12,16,19,22],'name':'E7','numeral':'II','octave':2,'octaveBass':false,'offset':4,'position':3,'root':'E','symbol':'7','type':'maj','voicing':'P5 R M3 P5 m7','voicingList':['P5','R','M3','P5','m7']}",
                "{'degree':1,'duration':3.5,'extension':'9','intervals':[-12,3,7,10,14],'name':'Emin9','numeral':'ii','octave':3,'octaveBass':false,'offset':16,'position':4,'root':'E','symbol':'min9','type':'min','voicing':'Root Position','voicingList':['R','m3','P5','m7','9']}",
                "{'degree':4,'duration':4.5,'extension':'13','intervals':[0,10,14,16,21],'name':'A13','numeral':'V','octave':2,'octaveBass':false,'offset':9,'position':5,'root':'A','symbol':'13','type':'maj','voicing':'R M3 m7 9 13','voicingList':['R','m7','9','M3','13']}",
                "{'degree':0,'duration':3.5,'extension':'6/9','intervals':[-12,4,7,9,14],'name':'D6/9','numeral':'I','octave':3,'octaveBass':false,'offset':14,'position':6,'root':'D','symbol':'6/9','type':'maj','voicing':'Root Position','voicingList':['R','M3','P5','M6','9']}",
                "{'degree':4,'duration':4.5,'extension':'7b13','intervals':[0,10,14,16,20],'name':'A7b13','numeral':'V','octave':2,'octaveBass':false,'offset':9,'position':7,'root':'A','symbol':'7b13','type':'maj','voicing':'R m7 9 M3 b13','voicingList':['R','m7','9','M3','b13']}"),


            "PremiumProgression:Jazz VI-V-III-iv:A:Minor:128:2024-11-18:fav_0" to listOf(
                "{'degree':3,'duration':3.0,'extension':'maj9','intervals':[-12,4,7,11,14],'name':'Fmaj9','numeral':'VI','octave':3,'octaveBass':false,'offset':17,'position':0,'root':'F','symbol':'maj9','type':'maj','voicing':'Root Position','voicingList':['R','M3','P5','M7','9']}",
                "{'degree':4,'duration':5.0,'extension':'7#9','intervals':[-12,4,7,10,15],'name':'E7#9','numeral':'V','octave':3,'octaveBass':false,'offset':16,'position':1,'root':'E','symbol':'7#9','type':'maj','voicing':'Root Position','voicingList':['R','M3','P5','m7','#9']}",
                "{'degree':0,'duration':3.0,'extension':'maj7(13)','intervals':[-12,9,11,16,19],'name':'Cmaj7(13)','numeral':'III','octave':3,'octaveBass':false,'offset':12,'position':2,'root':'C','symbol':'maj7(13)','type':'maj','voicing':'R 13 M7 M3 P5','voicingList':['R','13','M7','M3','P5']}",
                "{'degree':1,'duration':5.0,'extension':'6/9','intervals':[-12,9,12,14,17],'name':'D6/9sus4','numeral':'iv','octave':3,'octaveBass':false,'offset':14,'position':3,'root':'D','symbol':'6/9sus4','type':'sus4','voicing':'R M6 R 9 P4','voicingList':['R','M6','R','9','P4']}",
                "{'degree':3,'duration':3.0,'extension':'maj9','intervals':[-12,4,7,11,14],'name':'Fmaj9','numeral':'VI','octave':3,'octaveBass':false,'offset':17,'position':4,'root':'F','symbol':'maj9','type':'maj','voicing':'Root Position','voicingList':['R','M3','P5','M7','9']}",
                "{'degree':4,'duration':5.0,'extension':'7#9','intervals':[-12,4,7,10,15],'name':'E7#9','numeral':'V','octave':3,'octaveBass':false,'offset':16,'position':5,'root':'E','symbol':'7#9','type':'maj','voicing':'Root Position','voicingList':['R','M3','P5','m7','#9']}",
                "{'degree':5,'duration':3.0,'extension':'9','intervals':[-12,2,3,7,10],'name':'Amin9','numeral':'i','octave':3,'octaveBass':false,'offset':21,'position':6,'root':'A','symbol':'min9','type':'min','voicing':'R 9 m3 P5 m7','voicingList':['R','9','m3','P5','m7']}",
                "{'degree':4,'duration':5.0,'extension':'6','intervals':[-12,4,7,9,12],'name':'G6','numeral':'VII','octave':3,'octaveBass':false,'offset':19,'position':7,'root':'G','symbol':'6','type':'maj','voicing':'R M3 P5 M6 R','voicingList':['R','M3','P5','M6','R']}"),

            "PremiumProgression:Jazz VI-V-I-V:C:Minor:80:2024-10-15:fav_0" to listOf(
                "{'degree':5,'duration':4.0,'extension':'maj9','intervals':[0,11,16,19,26],'name':'G#maj9','numeral':'VI','octave':2,'offset':8,'position':0,'root':'G#','symbol':'maj9','type':'maj','voicing':'R M7 M3 P5 9','voicingList':['R','M7','M3','P5','9']}",
                "{'degree':4,'duration':4.0,'extension':'7#5#9','intervals':[0,10,16,20,27],'name':'G7#5#9','numeral':'V','octave':2,'offset':7,'position':1,'root':'G','symbol':'7#5#9','type':'maj','voicing':'R m7 M3 #5 #9','voicingList':['R','m7','M3','#5','#9']}",
                "{'degree':0,'duration':4.0,'extension':'9','intervals':[0,3,10,14,19],'name':'Cmin9','numeral':'I','octave':3,'offset':12,'position':2,'root':'C','symbol':'min9','type':'min','voicing':'R m3 m7 9 P5','voicingList':['R','m3','m7','9','P5']}",
                "{'degree':4,'duration':4.0,'extension':'13','intervals':[0,10,16,21,26],'name':'F13','numeral':'V','octave':2,'offset':5,'position':3,'root':'F','symbol':'13','type':'maj','voicing':'R m7 M3 13 9','voicingList':['R','m7','M3','13','9']}"),

            "PremiumProgression:Jazz iv-vII-i-bV:D:Minor:140:2024-10-15:fav_0" to listOf(
                "{'degree':3,'duration':4.0,'extension':'9','intervals':[0,10,15,19,26],'name':'Gmin9','numeral':'iv','octave':2,'octaveBass':false,'offset':7,'position':0,'root':'G','symbol':'min9','type':'min','voicing':'R m7 m3 P5 9','voicingList':['R','m7','m3','P5','9']}",
                "{'degree':4,'duration':4.0,'extension':'9#11','intervals':[0,7,16,22,26,30],'name':'D#9#11','numeral':'bII','octave':2,'octaveBass':false,'offset':3,'position':1,'root':'D#','symbol':'9#11','type':'maj','voicing':'R P5 M3 m7 9 #11','voicingList':['R','P5','M3','m7','9','#11']}",
                "{'degree':0,'duration':4.0,'extension':'9','intervals':[-12,3,7,10,14,19],'name':'Dmin9','numeral':'i','octave':3,'octaveBass':true,'offset':14,'position':2,'root':'D','symbol':'min9','type':'min','voicing':'R m3 P5 m7 9 P5','voicingList':['R','m3','P5','m7','9','P5']}",
                "{'degree':4,'duration':4.0,'extension':'13','intervals':[0,10,16,21,26],'name':'G#13','numeral':'bV','octave':2,'octaveBass':false,'offset':8,'position':3,'root':'G#','symbol':'13','type':'maj','voicing':'R m7 M3 13 9','voicingList':['R','m7','M3','13','9']}"),

            "PremiumProgression:RnB I-iv-bvii-I:C:Major:150:2024-10-03:fav_0" to listOf(
                "{'degree':0,'duration':3.0,'extension':'maj9','intervals':[0,7,11,14,16,19],'name':'Cmaj9','numeral':'I','octave':3,'offset':12,'position':0,'root':'C','symbol':'maj9','type':'maj','voicing':'R P5 M7 9 M3','voicingList':['R','P5','M7','9','M3','P5']}",
                "{'degree':0,'duration':5.0,'extension':'11','intervals':[0,3,5,7,10,14],'name':'Fmin11','numeral':'iv','octave':3,'offset':17,'position':1,'root':'F','symbol':'min11','type':'min','voicing':'R m3 11 P5 m7 9','voicingList':['R','m3','11','P5','m7','9']}",
                "{'degree':3,'duration':3.0,'extension':'9','intervals':[0,10,14,17,19],'name':'A#9sus4','numeral':'bvii','octave':2,'offset':10,'position':2,'root':'A#','symbol':'9sus4','type':'sus4','voicing':'R m7 9 P4 P5','voicingList':['R','m7','9','P4','P5']}",
                "{'degree':0,'duration':5.0,'extension':'maj9','intervals':[0,7,11,14,16,19],'name':'Cmaj9','numeral':'I','octave':3,'offset':12,'position':3,'root':'C','symbol':'maj9','type':'maj','voicing':'R P5 M7 9 M3 P5','voicingList':['R','P5','M7','9','M3','P5']}"),


            "PremiumProgression:i-VI:B:Minor:140:2024-12-01:fav_0" to listOf("{'degree':0,'duration':8.0,'extension':'9','intervals':[0,10,14,15,19],'name':'Bmin9','numeral':'i','octave':2,'octaveBass':false,'offset':11,'position':0,'root':'B','symbol':'min9','type':'min','voicing':'R m7 9 m3 P5','voicingList':['R','m7','9','m3','P5']}","{'degree':5,'duration':8.0,'extension':'maj9','intervals':[-12,2,4,7,11],'name':'Gmaj9','numeral':'VI','octave':3,'octaveBass':false,'offset':19,'position':1,'root':'G','symbol':'maj9','type':'maj','voicing':'R 9 M3 P5 M7','voicingList':['R','9','M3','P5','M7']}", "{'degree':0,'duration':8.0,'extension':'9','intervals':[0,10,14,15,19],'name':'Bmin9','numeral':'i','octave':2,'octaveBass':false,'offset':11,'position':2,'root':'B','symbol':'min9','type':'min','voicing':'R m7 9 m3 P5','voicingList':['R','m7','9','m3','P5']}","{'degree':5,'duration':8.0,'extension':'maj9','intervals':[-12,2,4,7,11],'name':'Gmaj9','numeral':'VI','octave':3,'octaveBass':false,'offset':19,'position':3,'root':'G','symbol':'maj9','type':'maj','voicing':'R 9 M3 P5 M7','voicingList':['R','9','M3','P5','M7']}"),

            "PremiumProgression:IV-iii-vi-V:C:Major:130:2024-12-01:fav_0" to listOf("{'degree':3,'duration':4.0,'extension':'maj7','intervals':[-12,4,7,11],'name':'Fmaj7','numeral':'IV','octave':3,'octaveBass':false,'offset':17,'position':0,'root':'F','symbol':'maj7','type':'maj','voicing':'Root Position','voicingList':['R','M3','P5','M7']}","{'degree':2,'duration':4.0,'extension':'7','intervals':[-12,3,7,10],'name':'Emin7','numeral':'iii','octave':3,'octaveBass':false,'offset':16,'position':1,'root':'E','symbol':'min7','type':'min','voicing':'Root Position','voicingList':['R','m3','P5','m7']}","{'degree':5,'duration':4.0,'extension':'7','intervals':[0,10,15,19],'name':'Amin7','numeral':'vi','octave':2,'octaveBass':false,'offset':9,'position':2,'root':'A','symbol':'min7','type':'min','voicing':'R m7 m3 P5','voicingList':['R','m7','m3','P5']}","{'degree':4,'duration':4.0,'extension':'6','intervals':[-12,0,4,9],'name':'G6','numeral':'V','octave':3,'octaveBass':false,'offset':19,'position':3,'root':'G','symbol':'6','type':'maj','voicing':'R R M3 M6','voicingList':['R','R','M3','M6']}"),

            "PremiumProgression:i-VI-V:C:Minor:130:2024-12-01:fav_0" to listOf("{'degree':0,'duration':8.0,'extension':'9','intervals':[0,7,14,15,22],'name':'Cmin9','numeral':'i','octave':3,'octaveBass':false,'offset':12,'position':0,'root':'C','symbol':'min9','type':'min','voicing':'R P5 9 m3 m7','voicingList':['R','P5','9','m3','m7']}","{'degree':5,'duration':4.0,'extension':'maj9','intervals':[0,11,14,16,19],'name':'G#maj9','numeral':'VI','octave':2,'octaveBass':false,'offset':8,'position':1,'root':'G#','symbol':'maj9','type':'maj','voicing':'R M7 9 M3 P5','voicingList':['R','M7','9','M3','P5']}","{'degree':4,'duration':4.0,'extension':'7(11)','intervals':[0,10,15,17,19],'name':'Gmin7(11)','numeral':'v','octave':2,'octaveBass':false,'offset':7,'position':2,'root':'G','symbol':'min7(11)','type':'min','voicing':'R m7 m3 11 P5','voicingList':['R','m7','m3','11','P5']}"),

            "PremiumProgression:i-iv-VI-v:A:Minor:140:2024-12-01:fav_0" to listOf("{'degree':0,'duration':3.0,'extension':'9','intervals':[0,10,14,15,19],'name':'Amin9','numeral':'i','octave':2,'octaveBass':false,'offset':9,'position':0,'root':'A','symbol':'min9','type':'min','voicing':'R m7 9 m3 P5','voicingList':['R','m7','9','m3','P5']}","{'degree':3,'duration':5.0,'extension':'9','intervals':[-12,3,7,10,14],'name':'Dmin9','numeral':'iv','octave':3,'octaveBass':false,'offset':14,'position':1,'root':'D','symbol':'min9','type':'min','voicing':'Root Position','voicingList':['R','m3','P5','m7','9']}","{'degree':5,'duration':3.0,'extension':'maj7(13)','intervals':[-12,4,7,9,11],'name':'Fmaj7(13)','numeral':'VI','octave':3,'octaveBass':false,'offset':17,'position':2,'root':'F','symbol':'maj7(13)','type':'maj','voicing':'R M3 P5 13 M7','voicingList':['R','M3','P5','13','M7']}","{'degree':4,'duration':5.0,'extension':'7','intervals':[-12,3,7,10,12],'name':'Emin7','numeral':'v','octave':3,'octaveBass':false,'offset':16,'position':3,'root':'E','symbol':'min7','type':'min','voicing':'R m3 P5 m7 R','voicingList':['R','m3','P5','m7','R']}")

        )
    }
}


